server:
  port: 10900 #程序启动端口,tomcat端口(可自定义)
spring:
  application:
    name: api-gateway-zuul #应用名称(别名)
  security:
    user:
      name: user
      password: 123456
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8761/eureka/    #defaultZone: http://username:password@localhost:8761/eureka/
  instance:
    prefer-ip-address: true #显示 ip
#security:  #配置访问 zuul 的 routes 的时候使用
#  user:
#    name: zuul
#    password: zuul
