server:
  port: 8080

spring:
  application:
    name: eureka-discovery

  security:
    user:
      name: user
      password: 123456

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8761/eureka/    #defaultZone: http://username:password@localhost:8761/eureka/